---
title: "Birasafab for tidytuesday"
date: 2022-02-09
output: html_document
editor_options: 
  chunk_output_type: console
---



```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidytuesdayR)
library(ggsankey)

```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.

```{r Load}

airmen <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-02-08/airmen.csv')

```



```{r Readme, eval = interactive()}

new_airmen %>% 
  count(graduated_from, sort = TRUE)

```

# organizing data to create a sankey diagram

```{r}
new_airmen = airmen %>% 
  filter(rank_at_graduation %in% c("2nd Lt","Flight Officer","1st Lt"))


sankey_data = new_airmen %>% 
  make_long(graduated_from,rank_at_graduation, pilot_type)

node_num = sankey_data %>% 
  group_by(node) %>% 
  count()

new_sankey_data = sankey_data %>% 
  left_join(node_num, by = "node")

```

# Ploting sankey diagram with available data
```{r}
new_sankey_data %>% 
  ggplot(aes(x = x, node = node, next_x = next_x, next_node = next_node, fill = factor(node)))+
  geom_sankey(flow.alpha = .5, show.legend = FALSE, color = "black")+
  geom_sankey_label(aes(label = paste0(node, ", n = ",n)), size = 3, fill = "yellow")+
  theme_light()+
  theme(axis.title = element_blank(),
    #    axis.text = element_blank(),
    axis.text.y = element_blank(),
        panel.grid = element_blank(),
        axis.ticks = element_blank(),
        panel.border = element_blank())+
  labs(title = "History of African-American pilots during World War II and beyond",
    subtitle = "Linkage between college graduated from, rank at graduation and Pilot type",
       caption = "Plot by Birasafab | Tidytuesday | Tuskegee Airmen")
```


# saving the created plot
```{r}

# This will save your most recent plot
ggsave(
  filename = "African-American pilots WWII.png",
  device = "png")


```
