---
title: "TidyTemplate"
date: 2022-02-21
output: html_document
editor_options: 
  chunk_output_type: console
---

# TidyTuesday
# Dubois Challenge  ---------------------------------------------------------------------------------

# Loading the package to be used ----------------------------------------------

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)


library(tidyverse)

```

# Creating the dataset of interest ----------------------------------------------

```{r}
data <-tribble(
        ~cat, ~Number, ~y_zero, ~color,~label,
        "1875",21186,25,"#FFCDCB", "1875________$ 21,186",
        "1880",498532,24,"#989eb4",  "1880________$ 498,532",
        "1885",736170,23,"#b08c71",  "1885________$ 736,170",
        "1890",1172624,22,"#ffc942", "1890________$ 1,173,624",
        "1895",1322694,21,"#efdecc", "1895________$ 1,322,694",
        "1899",1434975,20,"#f02c49", "1899________$ 1,434,975"
)


```

# Mine Graphic ----------------------------------------------
```{r}
data %>% 
  mutate(cat = fct_reorder(cat,-Number)) %>% 
  ggplot(aes(cat,Number, fill = I(color)), color = "black")+
  geom_bar(stat = "identity")+
  coord_polar(theta = "y")+
  ylim(0,1500000)+
  theme_void()
```

# Copied plot -------------------------------------------------------

# Slope

```{r}
slope = (20-6)/143495

```

#
```{r}
data = data %>% 
  mutate(y_final = y_zero-Number*slope )
```

# Polygons compositions ------------------------------------------------------------------

```{r}
positions = data %>% 
  mutate(x_1 = 0,
         x_2 = Number,
         x_3 = Number,
         x_4 = 0,
         y_1 = y_zero,
         y_2 = y_final,
         y_3 = y_final+1,
         y_4 = y_zero+1) %>% 
  select(cat, x_1:y_4) %>% 
  pivot_longer(cols = -cat,
               names_sep = "_",
               names_to = c("coord","rang")) %>% 
  pivot_wider(names_from = "coord", values_from = value)

```

# Joining with initial dataset ------------------------------------------------------------
```{r}
positions = positions %>% 
  left_join(data, by = "cat")
```

# first plot
```{r}
final_plot = positions %>% 
  ggplot(aes(x,y, group = cat))+
  geom_polygon(aes(group = cat, fill = I(color)), color = "black")+
  scale_y_continuous(expand=expansion(add=c(11,-5))) +
  scale_x_continuous(expand=expansion(add=c(0,-650000))) +
  coord_polar()+
  geom_text(data = . %>% filter(rang==1),
            aes(label = paste(label,"   ",sep="")),
            adj=1, nudge_y=.5, nudge_x = -0000, color="black",size=3,family="DecimaMonoPro")+
  theme_void()+
  labs(title = "ASSESSED VALUE OF HOUSEHOLD AND KITCHEN FURNITURE\nOWNED BY GEORGIA NEGROES.") + 
  theme(legend.position="none",
        text = element_text(family="I Sans Semibold"),
        plot.title = element_text(face = "bold", size = rel(1.75), hjust = .5),
        plot.margin = margin(c(.25,0,0,0), unit = "cm"))


# adding a layer to the final plot
cowplot::ggdraw(final_plot) + 
  theme(
        plot.background = element_rect(fill="#e9d9c9", color=NA)
  )
```

# Save Image ----------------------------------------------

 

```{r}

path = here::here("Week_07_plot")


ggsave(filename = glue::glue("{path}.png"), width = 9, height = 9, dpi = 300, device = "png")

```
