---
title: "TidyTemplate"
date: 2022-03-28
output: html_document
editor_options: 
  chunk_output_type: console
---

# TidyTuesday


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
# library(tidytuesdayR)

```

# Load the weekly Data

Download the weekly data and make available in the `tt` object.

```{r Load}
# the following code for downloading this week's dataset doesn't seem to work properly.
# tt <- tt_load("2022-03-22")

# downloading this week's data manually
# babynames <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-22/babynames.csv')

# saving the downloaded dataset
# write_csv(tt$nz_names, file = "nz_names.csv")
```

# Using the downloaded and saved files 
```{r}
# reading the new Zealand names
nz_names <- read_csv(file = "C:/Users/fabrice.birasa/Documents/My files/Learning/R learning/Tidytuesday2022/2022_week12/nz_names.csv")

# reading the new zealand lifetables

nz_lifetables <- read_csv(file = "C:/Users/fabrice.birasa/Documents/My files/Learning/R learning/Tidytuesday2022/2022_week12/nz_lifetables.csv")

# reading applicants dataset
applicants <- read_csv(file = "C:/Users/fabrice.birasa/Documents/My files/Learning/R learning/Tidytuesday2022/2022_week12/applicants.csv")

# reading births dataset
births <- read_csv(file = "C:/Users/fabrice.birasa/Documents/My files/Learning/R learning/Tidytuesday2022/2022_week12/births.csv")

# reading maorinames dataset
maorinames <- read_csv(file = "C:/Users/fabrice.birasa/Documents/My files/Learning/R learning/Tidytuesday2022/2022_week12/maorinames.csv")

# reading lifetables dataset
lifetables <- read_csv(file = "C:/Users/fabrice.birasa/Documents/My files/Learning/R learning/Tidytuesday2022/2022_week12/lifetables.csv")

# reading babynames dataset
babynames <- read_csv(file = "C:/Users/fabrice.birasa/Documents/My files/Learning/R learning/Tidytuesday2022/2022_week12/babynames.csv")

```

# Data wrangling
```{r}
babynames %>% 
  filter(year == 1880 | name == "Addie")
  count(year, name, sort = TRUE)
```
