---
title: "tweets dataset from tidytuesday project"
author: "birasafab"
date: "4/1/2022"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
```

# Importing the required dataset
link to the dataset used: https://github.com/rfordatascience/tidytuesday/releases/tag/tidytuesday_tweets-fcc8b6f
```{r}

tweets = read_csv(file = file.choose())%>% 
  mutate(year = year(created_at))
```

# data wrangling
```{r}
tweets_week = tweets  %>% 
  select(year, everything()) %>% 
  count(year, week)

tweets_week %>% 
  ggplot(aes(week,n, fill = year))+
  geom_col()+
  coord_polar(theta = "x")+
  labs(
    y = "Number  of tweets per week since 2018",
    x = "Weeek Number",
    caption = "Plot by Birasafab@gmail.com",
    subtitle = "Weekly # of tweets related to Tidytuesday since 2018 until now",
    title = "Level of participation in tidytuesday since 2018"
  )+
  theme(
    panel.background = element_rect(fill = "black"),
    plot.background = element_rect(fill = "#eab676"),
    axis.text.x = element_text(color = "white", size = 23),
    axis.text.y = element_text(color = "black", size = 23),
    axis.title= element_text(color = "black", size = 23),
    legend.background = element_rect(fill = "#e28743"),
    plot.caption = element_text(size = 15),
    plot.title = element_text(size = 23)
  )

# weekly faceted plot by year of observation
tweets_week %>% 
  filter(year != 2022) %>% 
  mutate(year = fct_reorder(factor(year),-n)) %>% 
  ggplot(aes(week,n))+
  geom_col( fill = "#bbe8ec")+
  coord_polar(theta = "x")+
  theme(
    panel.background = element_rect(fill = "black"),
    plot.background = element_rect(fill = "#eab676"),
    axis.text.x = element_text(color = "white", size = 13),
    axis.text.y = element_text(color = "black", size = 13),
    axis.title= element_text(color = "black", size = 16),
    legend.background = element_rect(fill = "#e28743"),
    plot.caption = element_text(size = 15)
  )+
  labs(
    y = "Number  of tweets per week since 2018",
    x = "Weeek Number",
    caption = "Plot by Birasafab@gmail.com",
    title = "Weekly participarticipation in Tidytuesday since 2018",
    subtitle = "Popularity of Tidytuesday Challenge increased overtime since 2018.  \n  Tidytuesday was even more popular in 2020 than it was in 2021"
  )+
  facet_wrap(~year)

# Level of Tidytuesday tuesday popularity by year

tweets %>% 
  count(year, sort = TRUE) %>% 
  mutate(year = fct_reorder(factor(year),n)) %>% 
  ggplot(aes(factor(year), n, fill = factor(year)))+
  geom_col()+
  coord_polar(theta = "y")+
    scale_y_continuous(limits = c(0,7000))+
  labs(
    fill = "Year",
    title = "What happened to Tidytuesday in 2021 compared to 2020?",
    subtitle = "What is behind the Popularity of Tidytuesday in 2020 more than 2021? \n 1) Outbreak of Covid-19? \n 2) Confinements?",
    y = "# of tweets ",
    x = "Year of observation"
  )+
  theme(
    panel.background = element_rect(fill = "black"),
    plot.background = element_rect(fill = "black"),
    axis.text = element_text(color = "#bce9ed", size = 17),
    axis.title = element_text(color = "#bce9ed", size = 17),
    axis.line= element_line(color = "#bce9ed"),
    axis.ticks= element_line(color = "#bce9ed"),
    legend.background = element_rect(fill = "#ed9951"),
    plot.title = element_text(color = "#bce9ed", size = 19),
    plot.subtitle = element_text(color = "#f1f0eb", size = 15))

# Monthly  faceted plot by year of observation


tweets_month = tweets %>% 
  mutate(month = month(created_at, label = TRUE, abbr = FALSE)) %>% 
  count(year,month)

tweets_month %>% 
  filter(year != 2022) %>% 
  mutate(year = fct_reorder(factor(year),-n)) %>% 
  ggplot(aes(month,n))+
  geom_col( fill = "#bbe8ec")+
  coord_polar(theta = "x")+
  labs(
    y = "#  of tweets per week since 2018",
    x = "Weeek Number",
    caption = "Plot by Birasafab@gmail.com",
    title = "Participation in Tidytuesday was popular in 2020 than 2021",
    subtitle = "# of monthly tweets related to Tidytuesday since 2018 \n "
  )+
  facet_wrap(~year)+
  theme(
    panel.background = element_rect(fill = "black"),
    plot.background = element_rect(fill = "#eab676"),
    axis.text.x = element_text(color = "white", size = 17),
    axis.text.y = element_text(color = "black", size = 13),
    axis.title= element_text(color = "black", size = 16),
    legend.background = element_rect(fill = "#e28743"),
    plot.caption = element_text(size = 15)
  )

# Top 10 popular month
tweets_month %>% 
  mutate(combine = paste0(month," ",year)) %>%
  mutate(combine = fct_reorder(combine,n)) %>% 
  arrange(desc(n)) %>% 
  head(10) %>% 
  ggplot(aes(n,combine))+
  geom_col(fill = "black")+
  geom_text(aes(label = n), size = 6, hjust = 1, color = "#bbe8ec")+
  labs(
    title = "Top 10 Months of Tidytuesday's participation popularity ",
    subtitle = "The month of July_2020 had the highest popularity",
    x = "# of tweets",
    y = "Month",
    caption = "Plot by Birasafab"
  )+
  theme(
    panel.background = element_blank(),
    plot.background = element_rect(fill = "#eab676"),
    panel.grid = element_blank(),
    axis.text = element_text(size = 14, colour = "black"),
    axis.title = element_text(size = 14),
    axis.ticks.y = element_blank()
  )
  
```
